// 景区数据（包含5A、4A景区、徒步路线、博物馆）
const scenicData = [
  // ========== 原5A景区数据保持不变（1-50） ==========
  {
    id: "1",
    name: "故宫博物院",
    province: "北京",
    city: "北京",
    lat: 39.916,
    lng: 116.403,
    ticket: "60元（旺季）",
    features: "明清皇家宫殿，世界文化遗产",
    route: "午门 → 太和殿 → 中和殿 → 保和殿 → 乾清宫 → 御花园",
    season: "春秋最佳",
    intro: "故宫是中国明清两代的皇家宫殿，旧称紫禁城，位于北京中轴线的中心。",
    category: "博物馆", // 新增分类
    level: "5A", // 新增等级
    duration: "3-4小时", // 新增游览时长
    tips: "提前7天预约，周一闭馆" // 新增小贴士
  },
  {
    id: "2",
    name: "八达岭长城",
    province: "北京",
    city: "北京",
    lat: 40.3587,
    lng: 116.016,
    ticket: "40元",
    features: "世界新七大奇迹，万里长城精华段",
    route: "关城 → 北一楼 → 北八楼（好汉坡）",
    season: "春秋季避开节假日",
    intro: "八达岭长城是明长城中保存最好的一段，是居庸关的前哨。",
    category: "古迹",
    level: "5A",
    duration: "3-4小时",
    tips: "建议乘坐缆车上下，穿舒适运动鞋"
  },
  // ... 其他原5A景区保持不变，但需要为每个景区添加新字段
  
  // ========== 浙江省新增数据 ==========
  // ----- 5A景区补充 -----
  {
    id: "101",
    name: "杭州西湖风景名胜区",
    province: "浙江",
    city: "杭州",
    lat: 30.246,
    lng: 120.130,
    ticket: "免费（部分景点收费）",
    features: "世界文化遗产，人间天堂",
    route: "断桥 → 白堤 → 苏堤 → 花港观鱼 → 雷峰塔",
    season: "四季皆宜，春秋最佳",
    intro: "西湖三面环山，湖中有三岛，以苏堤春晓、断桥残雪等十景闻名。",
    category: "自然风光",
    level: "5A",
    duration: "4-6小时",
    tips: "建议骑行或乘电瓶车游览，春季赏花最佳"
  },
  {
    id: "102",
    name: "普陀山风景名胜区",
    province: "浙江",
    city: "舟山",
    lat: 29.967,
    lng: 122.333,
    ticket: "160元（1-11月），140元（12月）",
    features: "观音菩萨道场，海天佛国",
    route: "普济寺 → 法雨寺 → 慧济寺 → 南海观音 → 紫竹林",
    season: "春秋最佳，农历二月十九观音诞辰",
    intro: "普陀山是中国四大佛教名山之一，四面环海，寺庙林立。",
    category: "宗教文化",
    level: "5A",
    duration: "2天",
    tips: "需乘船上岛，建议住一晚"
  },
  {
    id: "103",
    name: "乌镇古镇",
    province: "浙江",
    city: "嘉兴",
    lat: 30.743,
    lng: 120.483,
    ticket: "东栅110元，西栅150元，联票190元",
    features: "中国最后的枕水人家，江南水乡典范",
    route: "东栅：财神湾 → 茅盾故居 → 木心美术馆；西栅：草本染色坊 → 昭明书院 → 白莲塔",
    season: "春秋最佳，避开节假日",
    intro: "乌镇有1300年历史，完整保存着晚清和民国时期的水乡风貌。",
    category: "古镇",
    level: "5A",
    duration: "1-2天",
    tips: "西栅夜景很美，建议住西栅景区内"
  },
  {
    id: "104",
    name: "千岛湖风景区",
    province: "浙江",
    city: "杭州",
    lat: 29.583,
    lng: 119.000,
    ticket: "130元（旺季），110元（淡季）",
    features: "天下第一秀水，1078个岛屿",
    route: "中心湖区：梅峰岛 → 渔乐岛 → 月光岛；东南湖区：黄山尖 → 天池岛",
    season: "4-10月最佳",
    intro: "千岛湖是新安江水电站建成后形成的人工湖，水质中国第一。",
    category: "自然风光",
    level: "5A",
    duration: "1天",
    tips: "建议乘船游览，梅峰岛俯瞰全景"
  },
  {
    id: "105",
    name: "奉化溪口-雪窦山景区",
    province: "浙江",
    city: "宁波",
    lat: 29.667,
    lng: 121.283,
    ticket: "210元（联票）",
    features: "蒋氏故里，弥勒道场，山水风光",
    route: "蒋氏故居 → 雪窦山 → 千丈岩 → 弥勒大佛",
    season: "四季皆宜",
    intro: "溪口是蒋介石故乡，雪窦山为四明山支脉，有'四明第一山'之称。",
    category: "人文历史",
    level: "5A",
    duration: "1天",
    tips: "可品尝溪口千层饼"
  },
  {
    id: "106",
    name: "南浔古镇",
    province: "浙江",
    city: "湖州",
    lat: 30.867,
    lng: 120.417,
    ticket: "95元",
    features: "江南六大古镇之一，中西合璧建筑",
    route: "小莲庄 → 嘉业堂藏书楼 → 张石铭旧宅 → 百间楼",
    season: "春秋最佳",
    intro: "南浔以丝商闻名，保留了大量中西合璧的豪宅，文化底蕴深厚。",
    category: "古镇",
    level: "5A",
    duration: "4-5小时",
    tips: "百间楼清晨拍照最美"
  },
  {
    id: "107",
    name: "雁荡山风景名胜区",
    province: "浙江",
    city: "温州",
    lat: 28.367,
    lng: 121.067,
    ticket: "200元（联票）",
    features: "东南第一山，三山五岳之一",
    route: "灵峰 → 灵岩 → 大龙湫 → 方洞",
    season: "5-10月最佳，雨后瀑布壮观",
    intro: "雁荡山以山水奇秀闻名，被誉为'海上名山'，谢灵运曾在此任职。",
    category: "自然风光",
    level: "5A",
    duration: "2天",
    tips: "灵峰夜景是特色"
  },
  {
    id: "108",
    name: "天台山景区",
    province: "浙江",
    city: "台州",
    lat: 29.150,
    lng: 121.033,
    ticket: "国清寺免费，石梁飞瀑60元",
    features: "佛教天台宗发源地，活佛济公故里",
    route: "国清寺 → 石梁飞瀑 → 华顶森林公园",
    season: "四季皆宜，4-5月杜鹃花开",
    intro: "天台山是佛教天台宗祖庭，国清寺为隋代古刹，李白曾游历于此。",
    category: "宗教文化",
    level: "5A",
    duration: "1天",
    tips: "国清寺斋饭很有名"
  },
  {
    id: "109",
    name: "神仙居景区",
    province: "浙江",
    city: "台州",
    lat: 28.700,
    lng: 120.600,
    ticket: "110元（不含索道）",
    features: "李白《梦游天姥吟留别》原型地",
    route: "南门进 → 索道上山 → 南天桥 → 观音峰 → 卧龙桥 → 北海索道下",
    season: "四季皆宜，云雾缭绕如仙境",
    intro: "神仙居以奇峰、云海、飞瀑著称，新开发的如意桥惊险刺激。",
    category: "自然风光",
    level: "5A",
    duration: "4-5小时",
    tips: "建议上下都坐索道，穿防滑鞋"
  },
  {
    id: "110",
    name: "西塘古镇",
    province: "浙江",
    city: "嘉兴",
    lat: 30.933,
    lng: 120.883,
    ticket: "95元",
    features: "生活着的千年古镇，烟雨长廊",
    route: "环秀桥 → 烟雨长廊 → 石皮弄 → 西园 → 送子来凤桥",
    season: "春秋最佳，雨天更有意境",
    intro: "西塘有27座古桥，122条弄堂，廊棚长达2000米，是江南水乡的活化石。",
    category: "古镇",
    level: "5A",
    duration: "4-5小时",
    tips: "晚上酒吧很有特色"
  },

  // ----- 4A景区 -----
  {
    id: "201",
    name: "灵隐寺",
    province: "浙江",
    city: "杭州",
    lat: 30.238,
    lng: 120.095,
    ticket: "30元（飞来峰45元）",
    features: "千年古刹，济公出家地",
    route: "天王殿 → 大雄宝殿 → 药师殿 → 灵隐飞来峰造像",
    season: "四季皆宜",
    intro: "灵隐寺始建于东晋，是杭州最早的名刹，寺前飞来峰有五代至元代的石刻造像。",
    category: "宗教文化",
    level: "4A",
    duration: "2-3小时",
    tips: "早上8点前人少清静"
  },
  {
    id: "202",
    name: "宋城景区",
    province: "浙江",
    city: "杭州",
    lat: 30.167,
    lng: 120.133,
    ticket: "观众席300元，贵宾席330元",
    features: "宋文化主题公园，《宋城千古情》演出",
    route: "市井街 → 宋城河 → 千古情剧院 → 怪街 → 鬼屋",
    season: "全年开放",
    intro: "宋城还原了宋代都市风貌，大型歌舞《宋城千古情》是一生必看的演出。",
    category: "主题公园",
    level: "4A",
    duration: "3-4小时",
    tips: "下午入园，看完夜场演出再离开"
  },
  {
    id: "203",
    name: "杭州乐园",
    province: "浙江",
    city: "杭州",
    lat: 30.167,
    lng: 120.200,
    ticket: "160元",
    features: "长三角地区著名主题乐园",
    route: "玛雅部落 → 冒险岛 → 失落丛林 → 童话王国",
    season: "4-10月",
    intro: "杭州乐园有悬挂过山车、雨神之锤等惊险刺激的游乐项目。",
    category: "主题公园",
    level: "4A",
    duration: "4-5小时",
    tips: "避开周末和节假日"
  },
  {
    id: "204",
    name: "西溪国家湿地公园",
    province: "浙江",
    city: "杭州",
    lat: 30.267,
    lng: 120.050,
    ticket: "80元（电瓶船60元）",
    features: "中国首个国家湿地公园，三堤十景",
    route: "周家村 → 烟水渔庄 → 深潭口 → 秋雪庵 → 高庄",
    season: "春秋最佳，春季花朝节，秋季火柿节",
    intro: "西溪与西湖、西泠并称'三西'，有'杭州之肾'之称，电影《非诚勿扰》取景地。",
    category: "自然风光",
    level: "4A",
    duration: "3-4小时",
    tips: "建议乘船游览"
  },
  {
    id: "205",
    name: "六和塔",
    province: "浙江",
    city: "杭州",
    lat: 30.190,
    lng: 120.125,
    ticket: "20元（登塔另付10元）",
    features: "钱塘江畔千年古塔，镇压潮水",
    route: "塔基 → 塔身 → 塔刹 → 俯瞰钱塘江大桥",
    season: "四季皆宜，中秋观潮",
    intro: "六和塔始建于北宋，共七层，登塔可俯瞰钱塘江和钱塘江大桥。",
    category: "古迹",
    level: "4A",
    duration: "1-2小时",
    tips: "与钱塘江大桥一起游览"
  },
  {
    id: "206",
    name: "岳王庙",
    province: "浙江",
    city: "杭州",
    lat: 30.248,
    lng: 120.130,
    ticket: "25元",
    features: "纪念民族英雄岳飞的祠堂",
    route: "门厅 → 正殿 → 岳飞墓 → 启忠祠",
    season: "四季皆宜",
    intro: "岳王庙内有岳飞塑像和岳飞墓，墓前有秦桧等四奸臣跪像。",
    category: "人文历史",
    level: "4A",
    duration: "1小时",
    tips: "位于西湖边，可顺路游览"
  },
  {
    id: "207",
    name: "宁波天一阁博物馆",
    province: "浙江",
    city: "宁波",
    lat: 29.867,
    lng: 121.533,
    ticket: "30元",
    features: "中国现存最古老的私家藏书楼",
    route: "东明草堂 → 天一阁 → 尊经阁 → 千晋斋",
    season: "四季皆宜",
    intro: "天一阁建于明代，由范钦主持建造，藏书7万余卷，是亚洲最古老的图书馆。",
    category: "博物馆",
    level: "4A",
    duration: "2小时",
    tips: "可了解中国古代藏书文化"
  },
  {
    id: "208",
    name: "温州江心屿",
    province: "浙江",
    city: "温州",
    lat: 28.017,
    lng: 120.650,
    ticket: "30元",
    features: "中国四大名屿之一，诗之岛",
    route: "江心寺 → 东西双塔 → 英国驻温领事馆旧址",
    season: "四季皆宜",
    intro: "江心屿位于瓯江中，谢灵运、李白、杜甫等历代诗人曾留下诗篇。",
    category: "自然风光",
    level: "4A",
    duration: "2-3小时",
    tips: "傍晚可看瓯江日落"
  },
  {
    id: "209",
    name: "绍兴鲁迅故里",
    province: "浙江",
    city: "绍兴",
    lat: 29.983,
    lng: 120.567,
    ticket: "免费（需预约）",
    features: "鲁迅先生出生地，三味书屋百草园",
    route: "鲁迅祖居 → 鲁迅故居 → 百草园 → 三味书屋 → 鲁迅纪念馆",
    season: "四季皆宜",
    intro: "鲁迅故里保存了鲁迅笔下的许多场景，是了解鲁迅生平的重要场所。",
    category: "人文历史",
    level: "4A",
    duration: "2-3小时",
    tips: "可品尝绍兴黄酒和茴香豆"
  },
  {
    id: "210",
    name: "绍兴柯岩风景区",
    province: "浙江",
    city: "绍兴",
    lat: 30.033,
    lng: 120.483,
    ticket: "115元（含鉴湖、鲁镇）",
    features: "石文化、水文化、桥文化",
    route: "柯岩 → 鉴湖 → 鲁镇 → 香林",
    season: "四季皆宜",
    intro: "柯岩以云骨、石佛奇观闻名，鲁镇再现了鲁迅笔下的水乡小镇。",
    category: "自然风光",
    level: "4A",
    duration: "4小时",
    tips: "鲁镇有社戏表演"
  },

  // ----- 博物馆 -----
  {
    id: "301",
    name: "浙江省博物馆",
    province: "浙江",
    city: "杭州",
    lat: 30.251,
    lng: 120.133,
    ticket: "免费（需预约）",
    features: "浙江最大的综合性人文科学博物馆",
    route: "孤山馆区：陶瓷馆 → 漆器馆 → 常书鸿美术馆；武林馆区：越地长歌 → 钱江潮",
    season: "全年开放，周一闭馆",
    intro: "馆藏文物10万余件，有河姆渡文化陶器、良渚文化玉器、越王剑等国宝。",
    category: "博物馆",
    level: "4A",
    duration: "2-3小时",
    tips: "武林馆区更新更大，建议预约武林馆区"
  },
  {
    id: "302",
    name: "中国丝绸博物馆",
    province: "浙江",
    city: "杭州",
    lat: 30.233,
    lng: 120.133,
    ticket: "免费",
    features: "中国最大的丝绸专业博物馆",
    route: "丝路馆 → 蚕桑馆 → 织造馆 → 时装馆",
    season: "全年开放，周一上午闭馆",
    intro: "展示了中国五千年的丝绸历史，可看到古代织机操作演示。",
    category: "博物馆",
    level: "4A",
    duration: "2小时",
    tips: "位于西湖边，可顺路游览"
  },
  {
    id: "303",
    name: "中国茶叶博物馆",
    province: "浙江",
    city: "杭州",
    lat: 30.217,
    lng: 120.100,
    ticket: "免费",
    features: "中国唯一以茶为主题的国家级博物馆",
    route: "茶史厅 → 茶萃厅 → 茶事厅 → 茶具厅 → 茶俗厅",
    season: "全年开放，周一闭馆",
    intro: "博物馆位于龙井茶核心产区，可了解茶文化，品尝龙井茶。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "周边有龙井村，可体验采茶"
  },
  {
    id: "304",
    name: "宁波博物馆",
    province: "浙江",
    city: "宁波",
    lat: 29.817,
    lng: 121.533,
    ticket: "免费",
    features: "建筑大师王澍代表作，宁波历史文化",
    route: "东方神舟 → 明清竹刻 → 民窑瓷器 → 民俗馆",
    season: "全年开放，周一闭馆",
    intro: "建筑本身是最大亮点，用旧砖瓦打造的外墙极具特色，馆藏丰富。",
    category: "博物馆",
    level: "4A",
    duration: "2小时",
    tips: "建筑很适合拍照"
  },
  {
    id: "305",
    name: "温州博物馆",
    province: "浙江",
    city: "温州",
    lat: 27.983,
    lng: 120.700,
    ticket: "免费",
    features: "温州历史文化艺术殿堂",
    route: "历史馆 → 陶瓷馆 → 书画馆 → 工艺馆",
    season: "全年开放，周一闭馆",
    intro: "展示了温州从新石器时代到近代的历史，有丰富的瓯窑瓷器。",
    category: "博物馆",
    level: "4A",
    duration: "2小时",
    tips: "位于温州世纪广场旁"
  },
  {
    id: "306",
    name: "嘉兴博物馆",
    province: "浙江",
    city: "嘉兴",
    lat: 30.750,
    lng: 120.750,
    ticket: "免费",
    features: "马家浜文化、崧泽文化、良渚文化",
    route: "禾兴之源 → 沃土嘉禾 → 书画陈列",
    season: "全年开放，周一闭馆",
    intro: "以马家浜文化遗址出土文物为特色，展示了嘉兴七千年历史。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "了解嘉兴历史文化"
  },
  {
    id: "307",
    name: "湖州博物馆",
    province: "浙江",
    city: "湖州",
    lat: 30.867,
    lng: 120.083,
    ticket: "免费",
    features: "湖笔文化、丝绸文化、茶文化",
    route: "吴兴赋 → 湖州春秋 → 赵孟頫书画",
    season: "全年开放，周一闭馆",
    intro: "以湖笔制作技艺和丝绸文化为特色，有丰富的书画藏品。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "可了解湖笔制作工艺"
  },
  {
    id: "308",
    name: "绍兴博物馆",
    province: "浙江",
    city: "绍兴",
    lat: 30.000,
    lng: 120.567,
    ticket: "免费",
    features: "越国文化、兰亭书法",
    route: "越地春秋 → 会稽瓷珍 → 翰墨书香",
    season: "全年开放，周一闭馆",
    intro: "以越国青铜器、越窑青瓷和明清书画为馆藏特色。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "了解绍兴历史文化"
  },
  {
    id: "309",
    name: "金华市博物馆",
    province: "浙江",
    city: "金华",
    lat: 29.083,
    lng: 119.650,
    ticket: "免费",
    features: "婺州窑、黄宾虹艺术",
    route: "八婺古韵 → 神奇大地 → 乡土民风",
    season: "全年开放，周一闭馆",
    intro: "以婺州窑瓷器、黄宾虹书画作品为特色，展示了金华历史文化和民俗风情。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "位于金华古子城附近"
  },
  {
    id: "310",
    name: "中国黄酒博物馆",
    province: "浙江",
    city: "绍兴",
    lat: 30.017,
    lng: 120.567,
    ticket: "30元",
    features: "黄酒文化主题博物馆",
    route: "酒史厅 → 酒俗厅 → 酒技厅 → 酒窖",
    season: "全年开放",
    intro: "展示了黄酒的历史、酿造工艺和酒俗文化，可品尝正宗绍兴黄酒。",
    category: "博物馆",
    level: "4A",
    duration: "1.5小时",
    tips: "可购买特色黄酒"
  },

  // ----- 徒步路线 -----
  {
    id: "401",
    name: "徽杭古道（浙江段）",
    province: "浙江",
    city: "杭州",
    lat: 30.233,
    lng: 119.117,
    ticket: "62元",
    features: "中国十大徒步路线之一，古时徽商通道",
    route: "永来村 → 蓝天凹 → 上雪堂 → 下雪堂 → 黄茅培 → 江南第一关",
    distance: "约20公里",
    duration: "6-8小时",
    difficulty: "中等",
    intro: "徽杭古道始建于唐代，是古代徽商入浙经商的重要通道，沿途风光秀丽。",
    category: "徒步路线",
    level: "4A",
    tips: "建议从浙江段反穿，难度较小"
  },
  {
    id: "402",
    name: "莫干山徒步",
    province: "浙江",
    city: "湖州",
    lat: 30.617,
    lng: 119.867,
    ticket: "80元",
    features: "避暑胜地，民国别墅群",
    route: "庾村 → 剑池 → 芦花荡公园 → 武陵村 → 大坑景区",
    distance: "约15公里",
    duration: "5-6小时",
    difficulty: "简单",
    intro: "莫干山以竹、云、泉'三胜'和清、静、绿、凉'四优'著称，有200多栋民国别墅。",
    category: "徒步路线",
    level: "4A",
    tips: "可住山中民宿"
  },
  {
    id: "403",
    name: "天目山徒步",
    province: "浙江",
    city: "杭州",
    lat: 30.333,
    lng: 119.433,
    ticket: "140元",
    features: "大树王国，天然氧吧",
    route: "禅源寺 → 大树王 → 开山老殿 → 仙人顶",
    distance: "约12公里",
    duration: "4-5小时",
    difficulty: "简单到中等",
    intro: "天目山有'大树华盖闻九州'之誉，森林覆盖率99%以上，空气负离子含量极高。",
    category: "徒步路线",
    level: "4A",
    tips: "雨后空气更清新"
  },
  {
    id: "404",
    name: "仙居公盂徒步",
    province: "浙江",
    city: "台州",
    lat: 28.650,
    lng: 120.600,
    ticket: "免费",
    features: "华东最后的香格里拉",
    route: "前坑村 → 公盂村 → 公盂背 → 林坑村",
    distance: "约15公里",
    duration: "5-6小时",
    difficulty: "中等",
    intro: "公盂村坐落在海拔600米的山上，四面奇峰环绕，宛如世外桃源。",
    category: "徒步路线",
    level: "未评级",
    duration: "1天",
    tips: "可在村里农家住宿"
  },
  {
    id: "405",
    name: "楠溪江徒步",
    province: "浙江",
    city: "温州",
    lat: 28.417,
    lng: 120.700,
    ticket: "免费（部分景点收费）",
    features: "山水田园，古村落群",
    route: "岩头镇 → 芙蓉村 → 丽水街 → 狮子岩 → 苍坡村",
    distance: "约20公里",
    duration: "6-7小时",
    difficulty: "简单",
    intro: "楠溪江以水秀、岩奇、瀑多、村古闻名，沿途可欣赏田园风光和古村落。",
    category: "徒步路线",
    level: "4A",
    tips: "可分两天走，中间住岩头镇"
  },
  {
    id: "406",
    name: "四明山徒步",
    province: "浙江",
    city: "宁波",
    lat: 29.667,
    lng: 121.083,
    ticket: "免费",
    features: "唐诗之路，红枫樱花",
    route: "四明山镇 → 仰天湖 → 鹁鸪岩 → 丹山赤水",
    distance: "约18公里",
    duration: "5-6小时",
    difficulty: "中等",
    intro: "四明山是唐诗之路的重要节点，春季樱花、秋季红枫，风景如画。",
    category: "徒步路线",
    level: "4A",
    tips: "4月樱花季最美"
  },
  {
    id: "407",
    name: "东白山徒步",
    province: "浙江",
    city: "金华",
    lat: 29.550,
    lng: 120.267,
    ticket: "免费",
    features: "浙中最高峰，高山湿地",
    route: "东白湖镇 → 东白山 → 太白峰",
    distance: "约14公里",
    duration: "5小时",
    difficulty: "中等",
    intro: "东白山主峰太白峰海拔1194米，山顶有高山湿地和风车阵，视野开阔。",
    category: "徒步路线",
    level: "未评级",
    tips: "露营可看日出云海"
  },
  {
    id: "408",
    name: "栲栳山徒步",
    province: "浙江",
    city: "宁波",
    lat: 30.133,
    lng: 121.367,
    ticket: "免费",
    features: "杨梅之乡，古道古刹",
    route: "鸣鹤古镇 → 栲栳山 → 定水寺",
    distance: "约10公里",
    duration: "3-4小时",
    difficulty: "简单",
    intro: "栲栳山在慈溪，有千年古刹定水寺，6月可采杨梅。",
    category: "徒步路线",
    level: "未评级",
    tips: "6月杨梅成熟季节最佳"
  },
  {
    id: "409",
    name: "百山祖徒步",
    province: "浙江",
    city: "丽水",
    lat: 27.733,
    lng: 119.167,
    ticket: "80元",
    features: "浙江第二高峰，原始森林",
    route: "百山祖管理处 → 百山祖顶峰 → 茶木淤",
    distance: "约16公里",
    duration: "6小时",
    difficulty: "中等",
    intro: "百山祖海拔1856米，是瓯江、闽江源头，有大量珍稀动植物。",
    category: "徒步路线",
    level: "4A",
    tips: "需要专业向导"
  },
  {
    id: "410",
    name: "十里琅珰徒步",
    province: "浙江",
    city: "杭州",
    lat: 30.217,
    lng: 120.100,
    ticket: "免费",
    features: "龙井茶山，杭州最美登山路线",
    route: "龙井村 → 十里琅珰 → 五云山 → 云栖竹径",
    distance: "约8公里",
    duration: "3小时",
    difficulty: "简单",
    intro: "十里琅珰是西湖群山中最经典的徒步路线，穿行于龙井茶山之间，视野极佳。",
    category: "徒步路线",
    level: "未评级",
    tips: "从龙井村出发，下到云栖竹径"
  }
];

// 省市数据（根据 scenicData 自动生成）
const provinces = [...new Set(scenicData.map(s => s.province))].sort();
const cities = {};
scenicData.forEach(s => {
  if (!cities[s.province]) cities[s.province] = [];
  if (!cities[s.province].includes(s.city)) {
    cities[s.province].push(s.city);
  }
});


// 调试用
console.log('✅ data.js loaded! Total scenic spots:', scenicData.length);
// 从scenicData提取分类/等级（改为动态获取，不声明全局变量）
console.log('Categories:', [...new Set(scenicData.map(s => s.category))].sort());
console.log('Levels:', [...new Set(scenicData.map(s => s.level))].sort());